package packageLP2;

import java.awt.Color;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichelli
 */
public class Ficha extends javax.swing.JFrame {

    /**
     * Creates new form TesteFicha
     */
    private final ControladorFicha controlFicha;

    public Ficha(ControladorFicha control) {
        initComponents();
        controlFicha = control;
        initLabels();
    }

    private void initLabels() {
        invEquipUsarButton.setContentAreaFilled(false);
        invEquipUsarButton.setBorderPainted(false);
        invRemoverButton.setContentAreaFilled(false);
        invRemoverButton.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            buttonGroup1 = new javax.swing.ButtonGroup();
            jTabbedPane1 = new javax.swing.JTabbedPane();
            jLayeredPane3 = new javax.swing.JLayeredPane();
            FichaNivelLb = new javax.swing.JLabel();
            FichaNomelLb = new javax.swing.JLabel();
            FichaAncelLb = new javax.swing.JLabel();
            FichaPodLb = new javax.swing.JLabel();
            FichaCorrLb = new javax.swing.JLabel();
            FichaInsLb = new javax.swing.JLabel();
            FichaForLb = new javax.swing.JLabel();
            FichaIntLb = new javax.swing.JLabel();
            FichaAgiLb = new javax.swing.JLabel();
            FichaVonLb = new javax.swing.JLabel();
            FichaTamLb = new javax.swing.JLabel();
            FichaVidaLb = new javax.swing.JLabel();
            FichaDesLb = new javax.swing.JLabel();
            FichaPercLb = new javax.swing.JLabel();
            FichaDefLb = new javax.swing.JLabel();
            FichaDanoLb = new javax.swing.JLabel();
            FichaArmorELabel = new javax.swing.JLabel();
            FichaTaxaLb = new javax.swing.JLabel();
            lblIdade = new javax.swing.JLabel();
            btnIntelecto = new javax.swing.JButton();
            btnForca = new javax.swing.JButton();
            btnVontade = new javax.swing.JButton();
            btnAgilidade = new javax.swing.JButton();
            btnPercepcao = new javax.swing.JButton();
            FichaBacground = new javax.swing.JLabel();
            jLayeredPane1 = new javax.swing.JLayeredPane();
            jScrollPane2 = new javax.swing.JScrollPane();
            jTableArma = new javax.swing.JTable();
            jScrollPane3 = new javax.swing.JScrollPane();
            jTableConsumiveis = new javax.swing.JTable();
            jScrollPane5 = new javax.swing.JScrollPane();
            jTableArmadura = new javax.swing.JTable();
            invEquipUsarButton = new javax.swing.JButton();
            invRemoverButton = new javax.swing.JButton();
            fundoMochila = new javax.swing.JLabel();
            lblINTdinheiro = new javax.swing.JLabel();
            lblMoedas = new javax.swing.JLabel();
            lblDinheiro = new javax.swing.JLabel();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            lblFundoInventario = new javax.swing.JLabel();

            setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            setTitle("FICHA");
            setFocusTraversalPolicyProvider(true);
            setMaximumSize(new java.awt.Dimension(820, 699));
            setMinimumSize(new java.awt.Dimension(820, 699));
            setPreferredSize(new java.awt.Dimension(820, 699));
            setResizable(false);
            setSize(new java.awt.Dimension(820, 699));
            addWindowListener(new java.awt.event.WindowAdapter() {
                  public void windowClosed(java.awt.event.WindowEvent evt) {
                        formWindowClosed(evt);
                  }
            });
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTabbedPane1.setMaximumSize(new java.awt.Dimension(820, 700));
            jTabbedPane1.setMinimumSize(new java.awt.Dimension(820, 700));
            jTabbedPane1.setPreferredSize(new java.awt.Dimension(820, 670));
            jTabbedPane1.setRequestFocusEnabled(false);

            jLayeredPane3.setMaximumSize(new java.awt.Dimension(820, 700));
            jLayeredPane3.setMinimumSize(new java.awt.Dimension(820, 700));
            jLayeredPane3.setName(""); // NOI18N
            jLayeredPane3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            FichaNivelLb.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
            FichaNivelLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaNivelLb.setText("12");
            FichaNivelLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaNivelLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 80, 60));

            FichaNomelLb.setFont(new java.awt.Font("Old English Text MT", 3, 34)); // NOI18N
            FichaNomelLb.setForeground(new java.awt.Color(0, 0, 0));
            FichaNomelLb.setText("Nome do personagem");
            jLayeredPane3.add(FichaNomelLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 460, 50));

            FichaAncelLb.setFont(new java.awt.Font("Bookman Old Style", 2, 24)); // NOI18N
            FichaAncelLb.setForeground(new java.awt.Color(0, 0, 0));
            FichaAncelLb.setText("Ancestralidade");
            jLayeredPane3.add(FichaAncelLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 250, -1));

            FichaPodLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaPodLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaPodLb.setText("12");
            FichaPodLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaPodLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 70, 70));

            FichaCorrLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaCorrLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaCorrLb.setText("12");
            FichaCorrLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaCorrLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 50, 50));

            FichaInsLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaInsLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaInsLb.setText("12");
            FichaInsLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaInsLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 80, 30));

            FichaForLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaForLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaForLb.setText("12");
            FichaForLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaForLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 50, 40));

            FichaIntLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaIntLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaIntLb.setText("12");
            FichaIntLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaIntLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 50, 40));

            FichaAgiLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaAgiLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaAgiLb.setText("12");
            FichaAgiLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaAgiLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 50, 40));

            FichaVonLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaVonLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaVonLb.setText("12");
            FichaVonLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaVonLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 50, 40));

            FichaTamLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaTamLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaTamLb.setText("12");
            FichaTamLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaTamLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 80, 40));

            FichaVidaLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaVidaLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaVidaLb.setText("12");
            FichaVidaLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaVidaLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, 80, 40));

            FichaDesLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaDesLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaDesLb.setText("12");
            FichaDesLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaDesLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 80, 30));

            FichaPercLb.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
            FichaPercLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaPercLb.setText("12");
            FichaPercLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaPercLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 40, 40));

            FichaDefLb.setFont(new java.awt.Font("Rubik", 1, 32)); // NOI18N
            FichaDefLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaDefLb.setText("12");
            FichaDefLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaDefLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 70, -1));

            FichaDanoLb.setFont(new java.awt.Font("Rubik", 1, 32)); // NOI18N
            FichaDanoLb.setForeground(new java.awt.Color(255, 0, 0));
            FichaDanoLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaDanoLb.setText("12");
            FichaDanoLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaDanoLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 60, 60));

            FichaArmorELabel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
            jLayeredPane3.add(FichaArmorELabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 330, 50));

            FichaTaxaLb.setFont(new java.awt.Font("Rubik", 1, 32)); // NOI18N
            FichaTaxaLb.setForeground(new java.awt.Color(0, 204, 0));
            FichaTaxaLb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaTaxaLb.setText("12");
            FichaTaxaLb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLayeredPane3.add(FichaTaxaLb, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 550, 90, 60));

            lblIdade.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
            lblIdade.setForeground(new java.awt.Color(0, 0, 0));
            lblIdade.setText("12");
            jLayeredPane3.add(lblIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 120, 50));

            btnIntelecto.setBackground(new java.awt.Color(102, 51, 0));
            btnIntelecto.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
            btnIntelecto.setForeground(new java.awt.Color(0, 0, 204));
            btnIntelecto.setText("+2");
            btnIntelecto.setBorder(null);
            btnIntelecto.setBorderPainted(false);
            btnIntelecto.setContentAreaFilled(false);
            btnIntelecto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnIntelecto.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnIntelectoActionPerformed(evt);
                  }
            });
            jLayeredPane3.add(btnIntelecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 60, 50));

            btnForca.setBackground(new java.awt.Color(102, 51, 0));
            btnForca.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
            btnForca.setForeground(new java.awt.Color(0, 0, 204));
            btnForca.setText("+2");
            btnForca.setBorder(null);
            btnForca.setBorderPainted(false);
            btnForca.setContentAreaFilled(false);
            btnForca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnForca.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnForcaActionPerformed(evt);
                  }
            });
            jLayeredPane3.add(btnForca, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 50, 40));

            btnVontade.setBackground(new java.awt.Color(102, 51, 0));
            btnVontade.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
            btnVontade.setForeground(new java.awt.Color(0, 0, 204));
            btnVontade.setText("+2");
            btnVontade.setBorder(null);
            btnVontade.setBorderPainted(false);
            btnVontade.setContentAreaFilled(false);
            btnVontade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnVontade.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnVontadeActionPerformed(evt);
                  }
            });
            jLayeredPane3.add(btnVontade, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 60, 40));

            btnAgilidade.setBackground(new java.awt.Color(102, 51, 0));
            btnAgilidade.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
            btnAgilidade.setForeground(new java.awt.Color(0, 0, 204));
            btnAgilidade.setText("+2");
            btnAgilidade.setBorder(null);
            btnAgilidade.setBorderPainted(false);
            btnAgilidade.setContentAreaFilled(false);
            btnAgilidade.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnAgilidade.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnAgilidadeActionPerformed(evt);
                  }
            });
            jLayeredPane3.add(btnAgilidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 60, 40));

            btnPercepcao.setBackground(new java.awt.Color(102, 51, 0));
            btnPercepcao.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
            btnPercepcao.setForeground(new java.awt.Color(0, 0, 204));
            btnPercepcao.setText("+2");
            btnPercepcao.setBorder(null);
            btnPercepcao.setBorderPainted(false);
            btnPercepcao.setContentAreaFilled(false);
            btnPercepcao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            btnPercepcao.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnPercepcaoActionPerformed(evt);
                  }
            });
            jLayeredPane3.add(btnPercepcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 50, 40));

            FichaBacground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            FichaBacground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageLP2/Imagens/fichaParaLP2.png"))); // NOI18N
            jLayeredPane3.add(FichaBacground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 820, 770));

            jTabbedPane1.addTab("FICHA", jLayeredPane3);

            jLayeredPane1.setMaximumSize(new java.awt.Dimension(820, 700));
            jLayeredPane1.setMinimumSize(new java.awt.Dimension(820, 700));
            jLayeredPane1.setName(""); // NOI18N
            jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTableArma.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {

                  },
                  new String [] {
                        "Nome", "Modificador", "Dano", "Quantidade"
                  }
            ) {
                  Class[] types = new Class [] {
                        java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
                  };
                  boolean[] canEdit = new boolean [] {
                        false, false, false, false
                  };

                  public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                  }

                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                  }
            });
            jTableArma.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            jTableArma.getTableHeader().setReorderingAllowed(false);
            jTableArma.addFocusListener(new java.awt.event.FocusAdapter() {
                  public void focusGained(java.awt.event.FocusEvent evt) {
                        jTableArmaFocusGained(evt);
                  }
                  public void focusLost(java.awt.event.FocusEvent evt) {
                        jTableArmaFocusLost(evt);
                  }
            });
            jScrollPane2.setViewportView(jTableArma);

            jLayeredPane1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 570, 100));

            jTableConsumiveis.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {

                  },
                  new String [] {
                        "Itens", "Quantidade"
                  }
            ) {
                  Class[] types = new Class [] {
                        java.lang.String.class, java.lang.Integer.class
                  };
                  boolean[] canEdit = new boolean [] {
                        false, false
                  };

                  public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                  }

                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                  }
            });
            jTableConsumiveis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            jTableConsumiveis.getTableHeader().setReorderingAllowed(false);
            jTableConsumiveis.addFocusListener(new java.awt.event.FocusAdapter() {
                  public void focusGained(java.awt.event.FocusEvent evt) {
                        jTableConsumiveisFocusGained(evt);
                  }
            });
            jScrollPane3.setViewportView(jTableConsumiveis);
            if (jTableConsumiveis.getColumnModel().getColumnCount() > 0) {
                  jTableConsumiveis.getColumnModel().getColumn(0).setResizable(false);
                  jTableConsumiveis.getColumnModel().getColumn(1).setResizable(false);
            }

            jLayeredPane1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 290, 88));

            jTableArmadura.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {

                  },
                  new String [] {
                        "Itens", "Defesa", "Quantidade"
                  }
            ) {
                  Class[] types = new Class [] {
                        java.lang.String.class, java.lang.String.class, java.lang.Integer.class
                  };
                  boolean[] canEdit = new boolean [] {
                        false, false, false
                  };

                  public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                  }

                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                  }
            });
            jTableArmadura.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            jTableArmadura.getTableHeader().setReorderingAllowed(false);
            jTableArmadura.addFocusListener(new java.awt.event.FocusAdapter() {
                  public void focusGained(java.awt.event.FocusEvent evt) {
                        jTableArmaduraFocusGained(evt);
                  }
            });
            jScrollPane5.setViewportView(jTableArmadura);
            if (jTableArmadura.getColumnModel().getColumnCount() > 0) {
                  jTableArmadura.getColumnModel().getColumn(0).setResizable(false);
                  jTableArmadura.getColumnModel().getColumn(1).setResizable(false);
                  jTableArmadura.getColumnModel().getColumn(2).setResizable(false);
            }

            jLayeredPane1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 410, 100));

            invEquipUsarButton.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
            invEquipUsarButton.setText("Usar");
            invEquipUsarButton.setMaximumSize(new java.awt.Dimension(100, 40));
            invEquipUsarButton.setMinimumSize(new java.awt.Dimension(100, 40));
            invEquipUsarButton.setPreferredSize(new java.awt.Dimension(100, 40));
            invEquipUsarButton.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                        invEquipUsarButtonMousePressed(evt);
                  }
                  public void mouseReleased(java.awt.event.MouseEvent evt) {
                        invEquipUsarButtonMouseReleased(evt);
                  }
            });
            invEquipUsarButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        invEquipUsarButtonActionPerformed(evt);
                  }
            });
            jLayeredPane1.add(invEquipUsarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

            invRemoverButton.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
            invRemoverButton.setText("Remover");
            invRemoverButton.setMaximumSize(new java.awt.Dimension(100, 40));
            invRemoverButton.setMinimumSize(new java.awt.Dimension(100, 40));
            invRemoverButton.setPreferredSize(new java.awt.Dimension(100, 40));
            invRemoverButton.addMouseListener(new java.awt.event.MouseAdapter() {
                  public void mousePressed(java.awt.event.MouseEvent evt) {
                        invRemoverButtonMousePressed(evt);
                  }
                  public void mouseReleased(java.awt.event.MouseEvent evt) {
                        invRemoverButtonMouseReleased(evt);
                  }
            });
            invRemoverButton.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        invRemoverButtonActionPerformed(evt);
                  }
            });
            jLayeredPane1.add(invRemoverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 130, -1));

            fundoMochila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageLP2/Imagens/mochila.png"))); // NOI18N
            jLayeredPane1.add(fundoMochila, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 200, 480, 430));

            lblINTdinheiro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            lblINTdinheiro.setForeground(new java.awt.Color(255, 204, 0));
            lblINTdinheiro.setText("12");
            jLayeredPane1.add(lblINTdinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 40, 40));

            lblMoedas.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
            lblMoedas.setText("Moedas: ");
            jLayeredPane1.add(lblMoedas, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, 40));

            lblDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageLP2/Imagens/botao2.png"))); // NOI18N
            lblDinheiro.setText("Moedas: ");
            jLayeredPane1.add(lblDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 130, 60));

            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageLP2/Imagens/botao2.png"))); // NOI18N
            jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 130, 60));

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageLP2/Imagens/botao2.png"))); // NOI18N
            jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 130, 60));

            lblFundoInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/packageLP2/Imagens/ruas.png"))); // NOI18N
            jLayeredPane1.add(lblFundoInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            jTabbedPane1.addTab("INVENTARIO", jLayeredPane1);

            getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 700));

            pack();
      }// </editor-fold>//GEN-END:initComponents

    private JTable selecionado = null;
    private void invEquipUsarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invEquipUsarButtonActionPerformed
         int linha;
          String valorAr[];
          String atualiza[][];
          
          atualiza = new String[2][1];
          atualiza[0][0] = "/atualizarDano";

          if (selecionado != null) {
                linha = selecionado.getSelectedRow();
                if (!(linha == -1) && selecionado.getValueAt(linha, 0) != null) {

                      if (selecionado == jTableArmadura) {
                            FichaArmorELabel.setText((String) selecionado.getValueAt(linha, 0));

                            if (selecionado.getValueAt(linha, 1).toString().strip().charAt(0) == 'A') {
                                  valorAr = selecionado.getValueAt(linha, 1).toString().split("\\W");
                                  if (valorAr.length == 1) {
                                        FichaDefLb.setText(FichaAgiLb.getText());
                                  } else {
                                        valorAr[1] = valorAr[1].strip();
                                        FichaDefLb.setText(Integer.toString(Integer.parseInt(valorAr[1]) + Integer.parseInt(FichaAgiLb.getText().strip())));
                                  }
                            } else {
                                  FichaDefLb.setText((String) selecionado.getValueAt(linha, 1));
                            }

                      } else if (selecionado == jTableConsumiveis) {
                            try {
                                  int valor = Integer.parseInt(selecionado.getValueAt(linha, 1).toString());
                                  String consumivel = (String) selecionado.getValueAt(linha, 0);
                                  valor -= 1;
                                  enviarRem(selecionado.getValueAt(linha, 0).toString(), "CONSUMIVEL");

                                  int vida;
                                  if (consumivel.equalsIgnoreCase("POCAO CURA")) {
                                        vida = Integer.parseInt(FichaDanoLb.getText()) - Integer.parseInt(FichaTaxaLb.getText());
                                        if(vida >= 0)
                                                FichaDanoLb.setText(Integer.toString(vida));
                                        else
                                                FichaDanoLb.setText("0");
                                        
                                                atualiza[1][0] = FichaDanoLb.getText();
                                                controlFicha.getSaida().reset();
                                                controlFicha.getSaida().writeObject(atualiza);
                                  }
                                  if (consumivel.equalsIgnoreCase("POCAO PANACEIA")) {
                                        vida = Integer.parseInt(FichaDanoLb.getText()) - (2 * Integer.parseInt(FichaTaxaLb.getText()));
                                        if(vida >= 0)
                                                FichaDanoLb.setText(Integer.toString(vida));
                                        else
                                                FichaDanoLb.setText("0");
                                  
                                                atualiza[1][0] = FichaDanoLb.getText();
                                                controlFicha.getSaida().reset();
                                                controlFicha.getSaida().writeObject(atualiza);
                                  }

                                  if (valor == 0) {
                                        try {
                                              removeLinha(jTableConsumiveis, linha);
                                        } catch (PrinterException ex) {
                                              Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                  } else {
                                        selecionado.setValueAt(Integer.toString(valor), linha, 1);
                                  }
                            } catch (IOException ex) {
                                  Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
                            }
                      } else {
                            System.out.println("Errou a linha");
                      }
                }
          }
    }//GEN-LAST:event_invEquipUsarButtonActionPerformed

    public void enviarRem(String nomeItem, String tipoItem) throws IOException {
            String[][] mensagem = new String[1][3];
            mensagem[0][0] = "/removerInv";
            mensagem[0][1] = nomeItem;
            mensagem[0][2] = tipoItem;

            controlFicha.getSaida().writeObject(mensagem);
      }
    
    private void jTableConsumiveisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableConsumiveisFocusGained
        jTableArmadura.clearSelection();
        jTableArma.clearSelection();
        selecionado = jTableConsumiveis;
    }//GEN-LAST:event_jTableConsumiveisFocusGained

    private void jTableArmaduraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableArmaduraFocusGained
        jTableConsumiveis.clearSelection();
        jTableArma.clearSelection();
        selecionado = jTableArmadura;
    }//GEN-LAST:event_jTableArmaduraFocusGained

    private void jTableArmaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableArmaFocusGained
        jTableConsumiveis.clearSelection();
        jTableArmadura.clearSelection();
        selecionado = jTableArma;

        invEquipUsarButton.setEnabled(false);
    }//GEN-LAST:event_jTableArmaFocusGained

//Passar para um metodo separado para facilitar o uso e implementar um dialog pra confirmar a excluão do item.
    private void invRemoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invRemoverButtonActionPerformed
          int linha;
          int valor;

          if (selecionado != null) {
                linha = selecionado.getSelectedRow();
                if (!(linha == -1) && selecionado.getValueAt(linha, 0) != null) {

                      if (selecionado == jTableArmadura) {
                            try {
                                  if(!selecionado.getValueAt(linha, 0).toString().equalsIgnoreCase("ROUPAS") || (selecionado.getValueAt(linha, 0).toString().equalsIgnoreCase("ROUPAS") && (Integer.parseInt(selecionado.getValueAt(linha, 2).toString())) > 1)){
                                          valor = Integer.parseInt(selecionado.getValueAt(linha, 2).toString());
                                          valor -= 1;
                                          enviarRem(selecionado.getValueAt(linha, 0).toString(), "ARMADURA");
                                          if (valor == 0) {
                                                try {
                                                      if (selecionado.getValueAt(linha, 0).toString().equalsIgnoreCase(FichaArmorELabel.getText())) {
                                                            FichaArmorELabel.setText("");
                                                      }

                                                      FichaDefLb.setText(FichaAgiLb.getText());
                                                      removeLinha(jTableArmadura, linha);
                                                } catch (PrinterException ex) {
                                                      Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
                                                }
                                          } else {
                                                selecionado.setValueAt(valor, linha, 2);
                                          }
                                    }else{
                                          JOptionPane.showMessageDialog(null, "Você deve manter pelo menos 1 Roupa", "ERRO", ERROR_MESSAGE);
                                        
                                  }  
                                  }catch (IOException ex) {
                                          Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                    

                      } else if (selecionado == jTableConsumiveis) {
                            try {
                                  valor = Integer.parseInt(selecionado.getValueAt(linha, 1).toString());
                                  valor -= 1;
                                  enviarRem(selecionado.getValueAt(linha, 0).toString(), "CONSUMIVEL");

                                  if (valor == 0) {
                                        try {
                                              removeLinha(jTableConsumiveis, linha);
                                        } catch (PrinterException ex) {
                                              Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                  } else {
                                        selecionado.setValueAt(valor, linha, 1);
                                  }
                            } catch (IOException ex) {
                                  Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
                            }
                      } else if (selecionado == jTableArma) {
                            try {
                                  valor = Integer.parseInt(selecionado.getValueAt(linha, 3).toString());
                                  valor -= 1;
                                  enviarRem(selecionado.getValueAt(linha, 0).toString(), "ARMA");

                                  if (valor == 0) {
                                        try {
                                              removeLinha(jTableArma, linha);
                                        } catch (PrinterException ex) {
                                              Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                  } else {
                                        selecionado.setValueAt(valor, linha, 3);
                                  }
                            } catch (IOException ex) {
                                  Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
                            }
                      }
                }
          } else {
                System.out.println("Linha Invalida");
          }
    }//GEN-LAST:event_invRemoverButtonActionPerformed

    private void jTableArmaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableArmaFocusLost
        invEquipUsarButton.setEnabled(true);
    }//GEN-LAST:event_jTableArmaFocusLost

    private void invEquipUsarButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invEquipUsarButtonMousePressed
        invEquipUsarButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_invEquipUsarButtonMousePressed

    private void invEquipUsarButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invEquipUsarButtonMouseReleased
        invEquipUsarButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_invEquipUsarButtonMouseReleased

    private void invRemoverButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invRemoverButtonMousePressed
        invRemoverButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_invRemoverButtonMousePressed

    private void invRemoverButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invRemoverButtonMouseReleased
        invRemoverButton.setForeground(Color.BLACK);
    }//GEN-LAST:event_invRemoverButtonMouseReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controlFicha.setBotaoAtivo();
    }//GEN-LAST:event_formWindowClosed
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//          A PARTIR DAQUI, VC TEM QUE ENVIAR VIA SERVIDOR OS RESULTADOS EM CADA CASO
//          DE ROLAGEM DE DADO
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////ROLAGEM COM MODIFICADOR///////////////////////////////////////////////////
Dados dadinho = new Dados();
String [][] arrayResultados = new String [1][2];

    private void btnIntelectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntelectoActionPerformed
        try {
                int aux = dadinho.rolarD20();
                int aux2;

                System.out.println(aux);
                System.out.println(Integer.parseInt(btnIntelecto.getText()));
                System.out.println("TIROU: " + (aux + Integer.parseInt(btnIntelecto.getText()))); // teste

                aux2 = aux + Integer.parseInt(btnIntelecto.getText());

                arrayResultados[0][0] = "/resultadosD20";
                arrayResultados[0][1] = Integer.toString(aux2);
                controlFicha.getSaida().reset();
                controlFicha.getSaida().writeObject(arrayResultados);
          } catch (IOException ex) {
                Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
          }

    }//GEN-LAST:event_btnIntelectoActionPerformed

    private void btnAgilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgilidadeActionPerformed
       try {
                int aux = dadinho.rolarD20();
                int aux2;

                System.out.println(aux);
                System.out.println(Integer.parseInt(btnAgilidade.getText()));
                System.out.println("TIROU: " + (aux + Integer.parseInt(btnAgilidade.getText()))); // teste

                aux2 = aux + Integer.parseInt(btnAgilidade.getText());

                arrayResultados[0][0] = "/resultadosD20";
                arrayResultados[0][1] = Integer.toString(aux2);
                controlFicha.getSaida().reset();
                controlFicha.getSaida().writeObject(arrayResultados);
          } catch (IOException ex) {
                Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnAgilidadeActionPerformed

    private void btnVontadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVontadeActionPerformed
    try {
                int aux = dadinho.rolarD20();
                int aux2;

                System.out.println(aux);
                System.out.println(Integer.parseInt(btnVontade.getText()));
                System.out.println("TIROU: " + (aux + Integer.parseInt(btnVontade.getText()))); // teste

                aux2 = aux + Integer.parseInt(btnVontade.getText());

                arrayResultados[0][0] = "/resultadosD20";
                arrayResultados[0][1] = Integer.toString(aux2);
                controlFicha.getSaida().reset();
                controlFicha.getSaida().writeObject(arrayResultados);
          } catch (IOException ex) {
                Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnVontadeActionPerformed

    private void btnPercepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPercepcaoActionPerformed
        try {
                int aux = dadinho.rolarD20();
                int aux2;

                System.out.println(aux);
                System.out.println(Integer.parseInt(btnPercepcao.getText()));
                System.out.println("TIROU: " + (aux + Integer.parseInt(btnPercepcao.getText()))); // teste

                aux2 = aux + Integer.parseInt(btnPercepcao.getText());

                arrayResultados[0][0] = "/resultadosD20";
                arrayResultados[0][1] = Integer.toString(aux2);
                controlFicha.getSaida().reset();
                controlFicha.getSaida().writeObject(arrayResultados);
          } catch (IOException ex) {
                Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnPercepcaoActionPerformed

    private void btnForcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForcaActionPerformed
        try {
                int aux = dadinho.rolarD20();
                int aux2;

                System.out.println(aux);
                System.out.println(Integer.parseInt(btnForca.getText()));
                System.out.println("TIROU: " + (aux + Integer.parseInt(btnForca.getText()))); // testea

                aux2 = aux + Integer.parseInt(btnForca.getText());

                arrayResultados[0][0] = "/resultadosD20";
                arrayResultados[0][1] = Integer.toString(aux2);
                controlFicha.getSaida().reset();
                controlFicha.getSaida().writeObject(arrayResultados);
          } catch (IOException ex) {
                Logger.getLogger(Ficha.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_btnForcaActionPerformed
/////////////////////////////////////////////////////////////////////////////////////////////////////////////
    
    public JTable[] getTables() {
        JTable arrayTables[] = new JTable[3];

        arrayTables[0] = jTableArma;
        arrayTables[1] = jTableArmadura;
        arrayTables[2] = jTableConsumiveis;

        return arrayTables;
    }

    public int iteraTable(JTable table, String conteudo) throws PrinterException {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int retorno = model.getRowCount();
        model.insertRow(table.getRowCount(), new Object[]{conteudo});
        return retorno;
    }

    public void removeLinha(JTable table, int linha) throws PrinterException {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.removeRow(linha);
    }

    public JLabel[] getLabels() {
        
            JLabel arrayLabels[] = new JLabel[19];

            arrayLabels[0] = FichaNomelLb;
            arrayLabels[1] = lblIdade;
            arrayLabels[2] = FichaAncelLb;
            arrayLabels[3] = FichaForLb;
            arrayLabels[4] = FichaAgiLb;
            arrayLabels[5] = FichaIntLb;
            arrayLabels[6] = FichaVonLb;
            arrayLabels[7] = FichaVidaLb;
            arrayLabels[8] = FichaNivelLb;
            arrayLabels[9] = FichaInsLb;
            arrayLabels[10] = FichaCorrLb;
            arrayLabels[11] = FichaTamLb;
            arrayLabels[12] = FichaDesLb;
            arrayLabels[13] = FichaPodLb;
            arrayLabels[14] = FichaDanoLb;
            arrayLabels[15] = FichaTaxaLb;
            arrayLabels[16] = FichaPercLb;
            arrayLabels[17] = FichaDefLb;
            arrayLabels[18] = lblINTdinheiro;

            return arrayLabels;      
      }
          

    public JButton[] getButtons() {

        JButton arrayButton[] = new JButton[5];

        arrayButton[0] = btnForca;
        arrayButton[1] = btnAgilidade;
        arrayButton[2] = btnIntelecto;
        arrayButton[3] = btnVontade;
        arrayButton[4] = btnPercepcao;

        return arrayButton;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ficha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
    }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JLabel FichaAgiLb;
      private javax.swing.JLabel FichaAncelLb;
      private javax.swing.JLabel FichaArmorELabel;
      private javax.swing.JLabel FichaBacground;
      private javax.swing.JLabel FichaCorrLb;
      private javax.swing.JLabel FichaDanoLb;
      private javax.swing.JLabel FichaDefLb;
      private javax.swing.JLabel FichaDesLb;
      private javax.swing.JLabel FichaForLb;
      private javax.swing.JLabel FichaInsLb;
      private javax.swing.JLabel FichaIntLb;
      private javax.swing.JLabel FichaNivelLb;
      private javax.swing.JLabel FichaNomelLb;
      private javax.swing.JLabel FichaPercLb;
      private javax.swing.JLabel FichaPodLb;
      private javax.swing.JLabel FichaTamLb;
      private javax.swing.JLabel FichaTaxaLb;
      private javax.swing.JLabel FichaVidaLb;
      private javax.swing.JLabel FichaVonLb;
      private javax.swing.JButton btnAgilidade;
      private javax.swing.JButton btnForca;
      private javax.swing.JButton btnIntelecto;
      private javax.swing.JButton btnPercepcao;
      private javax.swing.JButton btnVontade;
      private javax.swing.ButtonGroup buttonGroup1;
      private javax.swing.JLabel fundoMochila;
      private javax.swing.JButton invEquipUsarButton;
      private javax.swing.JButton invRemoverButton;
      private javax.swing.JLabel jLabel1;
      private javax.swing.JLabel jLabel2;
      private javax.swing.JLayeredPane jLayeredPane1;
      private javax.swing.JLayeredPane jLayeredPane3;
      private javax.swing.JScrollPane jScrollPane2;
      private javax.swing.JScrollPane jScrollPane3;
      private javax.swing.JScrollPane jScrollPane5;
      private javax.swing.JTabbedPane jTabbedPane1;
      private javax.swing.JTable jTableArma;
      private javax.swing.JTable jTableArmadura;
      private javax.swing.JTable jTableConsumiveis;
      private javax.swing.JLabel lblDinheiro;
      private javax.swing.JLabel lblFundoInventario;
      private javax.swing.JLabel lblINTdinheiro;
      private javax.swing.JLabel lblIdade;
      private javax.swing.JLabel lblMoedas;
      // End of variables declaration//GEN-END:variables
}
